### ISSUE TITLE
HW_02_03

### ISSUE THREAD

**Issue by Gleb-Tocarenco** [dsharpminor/python#1]
https://github.com/dsharpminor/python/blob/c51cfb2a1677d0530d608286fa1e5911a82bbaee/Courses/Mentor/02_hw_03.py#L75

In this line you could use isalpha and isnumeric methods in for checking is string is a text either digit
https://www.w3schools.com/python/ref_string_isnumeric.asp#:~:text=The%20isnumeric()%20method%20returns,%2C%20and%20the%20%2D%20and%20the%20.

**Comment by adorite** [comment]
Thank you, got it! Can I still use .isnumeric() or .isalpha() if I don't want to consider zero and letters that are after 'h' in the alphabet?
